#配置dubbo服务
dubbo:
  application:
    #中心服务
    name: web-center
  registry:
    protocol: zookeeper
    address: 123.57.137.212:2181
server:
  port: 9090
spring:
  thymeleaf:
    cache: false
#上传文件
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 123.57.137.212:22122